# permissions for end users to edit post-installs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: post-install-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: studentapp
    app.kubernetes.io/part-of: studentapp
    app.kubernetes.io/managed-by: kustomize
  name: post-install-editor-role
rules:
- apiGroups:
  - app.pallavw.com
  resources:
  - post-installs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.pallavw.com
  resources:
  - post-installs/status
  verbs:
  - get
