# permissions for end users to view studentapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: studentapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: studentapp
    app.kubernetes.io/part-of: studentapp
    app.kubernetes.io/managed-by: kustomize
  name: studentapp-viewer-role
rules:
- apiGroups:
  - app.pallavw.com
  resources:
  - studentapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.pallavw.com
  resources:
  - studentapps/status
  verbs:
  - get
