# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/app.pallavw.com_studentapps.yaml
- bases/app.pallavw.com_pre-installs.yaml
- bases/app.pallavw.com_storages.yaml
- bases/app.pallavw.com_databases.yaml
- bases/app.pallavw.com_webapps.yaml
- bases/app.pallavw.com_post-installs.yaml
#+kubebuilder:scaffold:crdkustomizeresource
