---
- hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  collections:
    - kubernetes.core
    - operator_sdk.util
  tasks:
    - name:
      set_fact:
        meta:
          name: "{{ ansible_operator_meta.name }}"
          namespace: "{{ ansible_operator_meta.namespace }}"
    - import_roles:
      - name: pre-install
        import_roles:
      - name: storage
        import_roles:
      - name: database
        import_roles:
      - name: webapp
        import_roles:
      - name: post-install
